_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    ANGLES:
      - 0
  ROI_HEADS:
    NUM_CLASSES: 1